In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:

!mkdir -p content/data
!cp -r "/content/drive/MyDrive/Deep_Learning/proj_omer/deblurnerf_dataset/real_camera_motion_blur/blurball" /content/drive/MyDrive/Deep_Learning/proj_omer/Deblur-NeRF-master/data



In [11]:
import os
os.chdir('/content/drive/MyDrive/Deep_Learning/proj_omer/Deblur-NeRF-master')
!pwd

/content/drive/MyDrive/Deep_Learning/proj_omer/Deblur-NeRF-master


In [12]:
!pip install torch torchvision --upgrade

In [13]:
!pip install -r requirements.txt

In [17]:
# התקנת כלי עזר לקימפול מהיר
!pip install ninja

# התקנת tiny-cuda-nn להאצת ה-Hash Grid
!pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
#!pip install https://github.com/camenduru/wheels/releases/download/colab/tinycudann-1.7-cp310-cp310-linux_x86_64.whl



# התקנת שאר הספריות שהקוד שלך דורש
!pip install lpips tensorboardX imageio opencv-python scikit-image configargparse

  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-yydrivif
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-yydrivif
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 2e757bbe781db59c4980d389d7dccbf5edc09669
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tinycudann
  Running setup.py clean for tinycudann
Failed to build tinycudann
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (tinycudann)


In [ ]:
!python3 run_nerf.py --config configs/blurball/tx_blurball_NGP_new.txt

/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1323: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Using hash encoding: True
Using occupancy grid: True
Loaded image data (400, 600, 3, 27) [400.         600.         421.10768103]
Loaded data/ 10.847889476359242 29.73636276710649
Data:
(27, 3, 5) (27, 400, 600, 3) (27, 2)
HOLDOUT view is 6
Loaded llff (27, 400, 600, 3) (120, 3, 5) [400.      600.      421.10767] data/
LLFF holdout, 7
DEFINING BOUNDS
NEAR FAR 0.42887598 1.3062665
Found ckpts []
Not ndc!
train on image sequence of len = 27, 600x400
get rays
shuffle rays
done
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained'

In [ ]:
!python run_nerf.py --config configs/blurball/tx_blurball_NGP_new.txt --render_only

Traceback (most recent call last):
  File "/content/drive/MyDrive/Deep_Learning/proj_omer/Deblur-NeRF-master/run_nerf.py", line 7, in <module>
  File "/usr/local/lib/python3.12/dist-packages/torch/__init__.py", line 2804, in <module>
    from torch import _meta_registrations
  File "/usr/local/lib/python3.12/dist-packages/torch/_meta_registrations.py", line 12, in <module>
    from torch._decomp import (
  File "/usr/local/lib/python3.12/dist-packages/torch/_decomp/__init__.py", line 287, in <module>
    import torch._decomp.decompositions
  File "/usr/local/lib/python3.12/dist-packages/torch/_decomp/decompositions.py", line 17, in <module>
    import torch._prims as prims
  File "/usr/local/lib/python3.12/dist-packages/torch/_prims/__init__.py", line 564, in <module>
    asin = _make_elementwise_unary_prim(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/_prims/__init__.py", line 511, in _make_elementwise_unary_prim
    return _make_prim(

In [ ]:
!python run_nerf.py --config configs/blurball/tx_blurball_NGP_new.txt --render_only --render_test

Exception ignored in: <function _get_module_lock.<locals>.cb at 0x7c2aae8ef060>
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 445, in cb
KeyboardInterrupt: 
Traceback (most recent call last):
  File "/content/drive/MyDrive/Deep_Learning/proj_omer/Deblur-NeRF-master/run_nerf.py", line 7, in <module>
    import torch
  File "/usr/local/lib/python3.12/dist-packages/torch/__init__.py", line 2229, in <module>
    from torch import _VF as _VF, functional as functional  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/functional.py", line 8, in <module>
    import torch.nn.functional as F
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/__init__.py", line 8, in <module>
    from torch.nn.modules import *  # usort: skip # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .l

In [ ]:
!python3 run_nerf.py --config configs/blurball/tx_blurball_NGP_kernel.txt

/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1305: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Using hash encoding: True
Using occupancy grid: True
Loaded image data (400, 600, 3, 27) [400.         600.         421.10768103]
Loaded data/ 10.847889476359242 29.73636276710649
recentered (3, 5)
[[ 1.0000000e+00  6.4581251e-09  1.3332152e-08  1.1037897e-09]
 [-6.4581251e-09  1.0000000e+00 -4.0485069e-09 -2.7594742e-09]
 [-1.3332152e-08  4.0485069e-09  1.0000000e+00 -3.8632639e-09]]
Data:
(27, 3, 5) (27, 400, 600, 3) (27, 2)
HOLDOUT view is 6
Loaded llff (27, 400, 600, 3) (120, 3, 5) [400.      600.      421.10767] data/
LLFF holdout, 7
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['/content/drive/MyDrive/Deep_Learning/proj_omer/Deblur-NeRF-master/logs_e

In [ ]:
!python3 run_nerf.py --config configs/blurball/tx_blurball_NGP_finetune.txt

/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1305: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Using hash encoding: True
Using occupancy grid: True
Loaded image data (400, 600, 3, 27) [400.         600.         421.10768103]
Loaded data/ 10.847889476359242 29.73636276710649
recentered (3, 5)
[[ 1.0000000e+00  6.4581251e-09  1.3332152e-08  1.1037897e-09]
 [-6.4581251e-09  1.0000000e+00 -4.0485069e-09 -2.7594742e-09]
 [-1.3332152e-08  4.0485069e-09  1.0000000e+00 -3.8632639e-09]]
Data:
(27, 3, 5) (27, 400, 600, 3) (27, 2)
HOLDOUT view is 6
Loaded llff (27, 400, 600, 3) (120, 3, 5) [400.      600.      421.10767] data/
LLFF holdout, 7
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['/content/drive/MyDrive/Deep_Learning/proj_omer/Deblur-NeRF-master/logs_e

In [ ]:
!python3 run_nerf.py --config configs/blurball/tx_blurball_NGP_render.txt


python3: can't open file '/content/run_nerf.py': [Errno 2] No such file or directory


In [ ]:
!python run_nerf.py --config configs/blurball/tx_blurball_NGP_sharp.txt

/usr/local/lib/python3.12/dist-packages/torch/__init__.py:1305: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /pytorch/torch/csrc/tensor/python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)
Using hash encoding: True
Using occupancy grid: True
Loaded image data (400, 600, 3, 27) [400.         600.         421.10768103]
Loaded data/ 10.847889476359242 29.73636276710649
recentered (3, 5)
[[ 1.0000000e+00  6.4581251e-09  1.3332152e-08  1.1037897e-09]
 [-6.4581251e-09  1.0000000e+00 -4.0485069e-09 -2.7594742e-09]
 [-1.3332152e-08  4.0485069e-09  1.0000000e+00 -3.8632639e-09]]
Data:
(27, 3, 5) (27, 400, 600, 3) (27, 2)
HOLDOUT view is 6
Loaded llff (27, 400, 600, 3) (120, 3, 5) [400.      600.      421.10767] data/
LLFF holdout, 7
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['/content/drive/MyDrive/Deep_Learning/proj_omer/Deblur-NeRF-master/logs_e

In [ ]:
!ls

configs  LICENSE       lpips	   project.ipynb  requirements.txt     scripts
content  load_llff.py  metrics.py  __pycache__	  run_nerf_helpers.py
data	 logs_exp      NeRF.py	   README.md	  run_nerf.py
